resources:
  - name: dbp_repo1
    type: GitRepo
    configuration:
      gitProvider: rak_github                      # <-- replace with your integration
      path: raksha78/jfrog-pipelines-docker-sample    # <-- replace with your repository name
      branches:
        include: master

  - name: dbp_image1
    type: Image
    configuration:
      registry: rak_art                               # <-- replace with your artifactory integration
      sourceRepository: docker_local               # <-- required if registry is Artifactory
      imageName: pipelines.westus.cloudapp.azure.com:8082/docker_local/dbp  # < -- replace with your image path and name
      imageTag: latest
      autoPull: true
      
  - name: dbp_build_info1
    type: BuildInfo
    configuration:
      sourceArtifactory: rak_art
      buildName: dbp_build1
      buildNumber: 1    

#   - name: dbp_promoted_build_info
#     type: BuildInfo
#     configuration:
#       sourceArtifactory: rak_art
#       buildName: dbp_build
#       buildNumber: 1
      

pipelines:
  - name: pipeline_dbp_rak
    steps:
      - name: docker_build1
        type: DockerBuild
        configuration:
          affinityGroup: dbp_group
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: pipelines.westus.cloudapp.azure.com:8082/docker_local/dbp # replace with your image path and name
          dockerImageTag: ${run_number}
          inputResources:
            - name: dbp_repo1
          integrations:
            - name: rak_art                           # <-- replace with your artifactory integration

      - name: docker_push1
        type: DockerPush
        configuration:
          affinityGroup: dbp_group
          targetRepository: docker_local
          integrations:
            - name: rak_art                            # <-- replace with your artifactory integration
          inputSteps:
            - name: docker_build1
          outputResources:
            - name: dbp_image1

      - name: publish_dbp_build1
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: docker_push1
          outputResources:
            - name: dbp_build_info1

#       - name: promote_dbp_build1
#         type: PromoteBuild
#         configuration:
#           targetRepository: demo-pipelines
#           integrations:
#             - name: rak_art
#           inputResources:
#             - name: dbp_build_info1
#           outputResources:
#             - name: dbp_promoted_build_info

# resources:
#   - name: dbp_repo
#     type: GitRepo
#     configuration:
#       gitProvider: firstGitHub   # replace with your integration
#       path: raksha78/jfrog-pipelines-docker-sample    # replace with your repository name
#       branches:
#         include: master
 
#   - name: dbp_image
#     type: Image
#     configuration:
#       registry: firstArtifactory      # replace with your Artifactory integration
#       sourceRepository: docker_local   # required if registry is Artifactory
#       imageName: 192.168.50.2:8082/artifactory/docker_local/mydockerbase  # replace with your image path and name
#       imageTag: latest
#       autoPull: true
      
# pipelines:
#   - name: pipeline_dbp
#     configuration:
#       nodePool: firstPool
#     steps:
#       - name: docker_build
#         type: DockerBuild
#         configuration:
#           affinityGroup: dbp_group
#           dockerFileLocation: .
#           dockerFileName: Dockerfile
#           dockerImageName: 192.168.50.2:8082/artifactory/docker_local/mydockerbase  # replace with your image path and name
#           dockerImageTag: ${run_number}
#           inputResources:
#             - name: dbp_repo
#           integrations:
#             - name: firstArtifactory    # replace with your artifactory integration
 
#       - name: docker_push
#         type: DockerPush
#         configuration:
#           affinityGroup: dbp_group
#           targetRepository: docker_local
#           integrations:
#             - name: firstArtifactory    # replace with your artifactory integration
#           inputSteps:
#             - name: docker_build
#           outputResources:
#             - name: dbp_image
