resources:
  - name: dbp_repo_01
    type: GitRepo
    configuration:
      gitProvider: raksha78_github                      # <-- replace with your integration
      path: raksha78/jfrog-pipelines-docker-sample    # <-- replace with your repository name
      branches:
        include: master

  - name: dbp_image_01
    type: Image
    configuration:
      registry: art_v                               # <-- replace with your artifactory integration
      sourceRepository: rak_docker              # <-- required if registry is Artifactory
      imageName: dev.jfrog-pipelines.com/rak_docker/dbp # < -- replace with your image path and name
      imageTag: latest
      autoPull: true
      
  - name: dbp_build_info_01
    type: BuildInfo
    configuration:
      sourceArtifactory: art_v
      buildName: dbp_build_rak_1
      buildNumber: 1    

pipelines:
  - name: pipeline_dbp_rak
    steps:
      - name: docker_build_01
        type: DockerBuild
        configuration:
          affinityGroup: dbp_group_001
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: dev.jfrog-pipelines.com/rak_docker/dbp  # replace with your image path and name
          dockerImageTag: ${run_number}
          inputResources:
            - name: dbp_repo_01
          integrations:
            - name: art_v                           # <-- replace with your artifactory integration

      - name: docker_push_01
        type: DockerPush
        configuration:
          affinityGroup: dbp_group_001
          targetRepository: rak_docker
          integrations:
            - name: art_v                            # <-- replace with your artifactory integration
          inputSteps:
            - name: docker_build_01
          outputResources:
            - name: dbp_image_01
            
      - name: publish_dbp_build_01
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: docker_push_01
          outputResources:
            - name: dbp_build_info_01

   
